### ISSUE TITLE
Got strange error messages while using pyBGPStream

### ISSUE THREAD

**Issue by aisavnin** [CAIDA/bgpstream#7] opened 2016-02-29 21:28 UTC
Got error messages like:
(actually much more of)

2016-02-29 09:24:41 [error] bgpdump_read_next: http://archive.routeviews.org/route-views4/bgpdata/2016.02/RIBS/rib.20160227.1000.bz2 incomplete dump record (803 bytes read, expecting 1416)

(also for this message strange - i'v asked for 2 hours before now, but files in logs are 2 days before) 

and 
Unexpected EOF while reading compressed file -- file is probably incomplete
Unexpected EOF while reading compressed file -- file is probably incomplete

and even 

`ERROR:

 Root object is not JSON
INFO: JSON: <!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 394205</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

ERROR: Invalid JSON response received from broker
WARN: Broker request failed, waiting 512s before retry
`

**Comment by chiaraorsini** [comment] 2016-02-29 22:29
Could you please share the python script (or at least the stream configuration part) so that we can try to reproduce the error?

Thanks.

**Comment by aisavnin** [comment] 2016-03-01 06:22
So, here is piece of code. (from tutorial, i think)
I'v reviewed it, and see that interval is too big, so no more question about "2 day before"
But error messages still repeats (in lesser amounts, and no varnish errors).
Could it be caused by too big (> 4 G) temporary files?
Script is running at Amazon instance in N. Virginia, so i do not expect any network troubles.

 t = int(time()) 
 stream = BGPStream()
 rec = BGPRecord()
 stream.add_filter('record-type','ribs')
 offset = 3600*24
 stream.add_interval_filter(t - offset*2, t)
 stream.add_rib_period_filter(offset*2)
 stream.start()
 edge_peer_asn = dict()
 while(stream.get_next_record(rec)):

**Comment by aisavnin** [comment] 2016-03-01 22:59
Well, it's not just error messages. Script also stops, seems awaiting for some kind of timeout.

**Comment by alistairking** [comment] 2016-04-26 21:31
Sorry, I didn't realize that I hadn't replied to this.
Are you still having these problems?

**Comment by aisavnin** [comment] 2016-04-27 06:17
Better late than never ;)

Yes, i still getting error messages (some last ones below, i keep
logfile for all i'v got, could attach, if you would like):

Alexander

2016-04-27 00:18:56 [error] bgpdump_read_next:
http://archive.routeviews.org/bgpdata/2016.04/RIBS/rib.20160426.2000.bz2
incomplete dump record (2854 bytes read, expecting 3250)

2016-04-27 00:20:05 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.sydney/bgpdata/2016.04/RIBS/rib.20160426.2000.bz2
incomplete dump record (232 bytes read, expecting 393)

2016-04-27 00:20:54 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.eqix/bgpdata/2016.04/RIBS/rib.20160426.2000.bz2
incomplete dump record (102 bytes read, expecting 774)

Unexpected EOF while reading compressed file -- file is probably incomplete

Unexpected EOF while reading compressed file -- file is probably incomplete

Unexpected EOF while reading compressed file -- file is probably incomplete

2016-04-27 00:27:44 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc03/2016.04/bview.20160427.0000.gz
incomplete dump record (545 bytes read, expecting 549)

2016-04-27 00:28:10 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc11/2016.04/bview.20160427.0000.gz
incomplete dump record (55 bytes read, expecting 496)

2016-04-27 00:28:20 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc10/2016.04/bview.20160427.0000.gz
incomplete dump record (403 bytes read, expecting 568)

Unexpected EOF while reading compressed file -- file is probably incomplete

Unexpected EOF while reading compressed file -- file is probably incomplete

Unexpected EOF while reading compressed file -- file is probably incomplete

2016-04-27 00:29:22 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc01/2016.04/bview.20160427.0000.gz
incomplete dump record (308 bytes read, expecting 645)

2016-04-27 00:29:24 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc04/2016.04/bview.20160427.0000.gz
incomplete dump record (502 bytes read, expecting 589)

2016-04-27 00:29:25 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc12/2016.04/bview.20160427.0000.gz
incomplete dump record (722 bytes read, expecting 849)

2016-04-27 0:31 GMT+03:00 Alistair King <notifications@github.com>:

**Comment by reuteran** [comment] 2016-05-18 18:24
I am getting similar messages (sometimes) when reading a file:
`bgpreader -w 0,-2 -d singlefile -o rib-file,latest-rv.bz2`
 2016-05-18 20:19:45 [error] bgpdump_read_next: latest-rv.bz2 incomplete dump record (247 byte read,  expecting 1159743572)

**Comment by alistairking** [comment] 2016-05-19 20:18
@reuteran that message should indicate a corrupted MRT file (libbgpdump has parsed an MRT header which indicates a message of length 1159743572 but there was only 247 bytes left in the file).

**Comment by wicaksana** [comment] 2016-06-02 11:05
I notice most of the time I get similar error (incomplete dump record) for most of collector's files. 

Which is most likely the problem? Is it the file stored in the repository, or the download process?

**Comment by alistairking** [comment] 2016-06-13 16:37
I _finally_ saw this message the other day, thought I haven't been able to reproduce the problem again. If anyone has a simple way to reproduce, I'd really appreciate it.

**Comment by aisavnin** [comment] 2016-06-14 09:16
Logs i'v got last night follows.
It's same script i'v provided in the beginтing of the ticket.
Amazon instance, 8G mem, 4G disk free.

Any possibility to turn on MORE logs?

2016-06-14 00:10:59 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views4/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (224 bytes read, expecting 1556)

2016-06-14 00:11:26 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views3/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (743 bytes read, expecting 817)

2016-06-14 00:11:39 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.isc/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (293 bytes read, expecting 351)

2016-06-14 00:12:02 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.telxatl/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (99 bytes read, expecting 316)

2016-06-14 00:12:05 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.saopaulo/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (620 bytes read, expecting 1474)

2016-06-14 00:12:12 [error] bgpdump_read_next:
http://archive.routeviews.org/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (330 bytes read, expecting 2255)

2016-06-14 00:13:29 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.sydney/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (184 bytes read, expecting 401)

2016-06-14 00:13:49 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.eqix/bgpdata/2016.06/RIBS/rib.20160613.1800.bz2
incomplete dump record (196 bytes read, expecting 689)

2016-06-14 00:21:14 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.sydney/bgpdata/2016.06/RIBS/rib.20160613.2000.bz2
incomplete dump record (128 bytes read, expecting 577)

2016-06-14 00:24:29 [error] bgpdump_read_next:
http://archive.routeviews.org/route-views.eqix/bgpdata/2016.06/RIBS/rib.20160613.2000.bz2
incomplete dump record (229 bytes read, expecting 606)

2016-06-14 00:29:06 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc07/2016.06/bview.20160614.0000.gz
incomplete dump record (135 bytes read, expecting 313)

2016-06-14 00:29:12 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc04/2016.06/bview.20160614.0000.gz
incomplete dump record (45 bytes read, expecting 408)

2016-06-14 00:29:30 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc10/2016.06/bview.20160614.0000.gz
incomplete dump record (303 bytes read, expecting 570)

2016-06-14 00:30:28 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc00/2016.06/bview.20160614.0000.gz
incomplete dump record (538 bytes read, expecting 724)

2016-06-14 00:30:38 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc01/2016.06/bview.20160614.0000.gz
incomplete dump record (362 bytes read, expecting 654)

2016-06-14 00:30:44 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc12/2016.06/bview.20160614.0000.gz
incomplete dump record (880 bytes read, expecting 885)

2016-06-14 00:30:45 [error] bgpdump_read_next:
http://data.ris.ripe.net/rrc11/2016.06/bview.20160614.0000.gz
incomplete dump record (468 bytes read, expecting 556)

2016-06-13 19:37 GMT+03:00 Alistair King <notifications@github.com>:

**Comment by alistairking** [comment] 2016-06-14 16:33
@aisavnin I think the issue that you are having may be due to the archive servers timing out your connections. Can you try the same processing but use only a single collector rather than all collectors and see if the errors go away?

**Comment by aisavnin** [comment] 2016-06-15 09:42
Well, when i test on single route-views.sfmix - no errors.

Is it possible to increase logs verbosity?


2016-06-14 19:33 GMT+03:00 Alistair King <notifications@github.com>:

**Comment by reuteran** [comment] 2016-08-18 12:35
Is there anything that can be done against this? I keep getting a lot of these errors when using routeviews + ripe ris as a source (all collectors). Right now Im just downloading the bgp data one collector at a time, which works without errors.

**Comment by alistairking** [comment] 2016-08-18 14:13
Unfortunately the correct fix is not trivial, and I don't have any spare cycles to work on it this month.
However, there may be a temporary workaround that I can put into place to help you guys out. Let me talk to the folks here today and I'll get back to you ASAP.

**Comment by reuteran** [comment] 2016-08-19 10:40
Tried it today with ris + routeviews projects, no more errors! Thank you

**Comment by alistairking** [comment] 2017-01-23 18:34
Since we haven't had any more complaints, I'm going to close this issue. Please feel free to reopen it if needed.

**Closed by alistairking** 2017-01-23 18:34 UTC

**Comment by alistairking** [comment] 2018-08-10 22:47
As a heads-up for folks who were experiencing this problem, we have finally implemented a permanent fix for this issue and will revert the temporary workaround that is currently in place on the broker next week.

The fix is implemented as part of the wandio library, so please install the latest version of wandio (4.0.0) from https://research.wand.net.nz/software/libwandio.php (you will then need to re-compile bgpstream).

I'll be reverting the temporary workaround on Monday (August 13) Pacific time unless I hear otherwise. So if think you're still affected, *and* won't have a chance to upgrade wandio before then please let me know and we can postpone.
