### ISSUE TITLE
Have problem linking with libbgpstream

### ISSUE THREAD

**Issue by ksalamat** [CAIDA/bgpstream#76] opened 2018-11-19 10:43 UTC
I have correctly installed BGPStream and I have a python code that works correctly using it. I want to develop a C++ code using the library but keep received messages like :
Undefined symbols for architecture x86_64:
  "bgpstream_start(struct_bgpstream_t*)", referenced from:
For all my calledBGPStream calls. 

The library are correctly installed and referred in the linker process by -lbgpstream. 

Important point I am in Mac and using Mojave. Any ideas ?

**Comment by digizeph** [comment] 2018-11-19 15:40
Not sure about the Mac environment, but I suspect that it the library path is not set correctly. 

- If you know where the library files are installed to, can you also try adding an option like to the following to specify the library location? `-L/opt/local/lib`

Thanks

**Comment by ksalamat** [comment] 2018-11-20 21:42
No if it was the case, I would have a "library libbgpstream not found". The library is found but no success

**Comment by ksalamat** [comment] 2018-11-22 22:58
Update. When I write a C program everything is fine. When I write a C++ program and use g++ for compilation the libraries are not found. Have also checked on linux and I have similar issue !

**Comment by alistairking** [comment] 2018-11-27 00:49
Closing this as it seems to be a duplicate of #61 
Feel free to re-open if not.

**Closed by alistairking** 2018-11-27 00:49 UTC
