### ISSUE TITLE
./configure wandio HTTP ERROR

### ISSUE THREAD

**Issue by Intissar-Addali** [CAIDA/bgpstream#89] opened 2019-06-18 08:35 UTC
Hello,
I am trying to install wandio following these instructions:
curl -O https://research.wand.net.nz/software/wandio/wandio-4.2.1.tar.gz
tar zxf wandio-4.2.1.tar.gz
cd wandio-4.2.1/
./configure
make
sudo make install
sudo ldconfig

but I got a http error after trying running "wandiocat http://google.com".
Otherwise, the run of ./configure shows these results:
configure: WANDIO version 4.2.1
configure: Compiled with compressed file (zlib) support: Yes
configure: Compiled with compressed file (bz2) support: Yes
configure: Compiled with compressed file (lzo write only) support: No
configure: Compiled with compressed file (lzma) support: No
configure: Compiled with compressed file (zstd) support: No
configure: Compiled with compressed file (lz4) support: No
configure: Compiled with Intel QuickAssist Technology support: No
configure: Compiled with http read (libcurl) support: Yes

Thank you in advance for your help.

**Comment by digizeph** [comment] 2019-06-18 18:10
Hi Intissar,

Thanks for reaching out and providing the detailed information on this issue. Unfortunately, I couldn't reproduce the errors you had. Here is what I did.

On a Fresh Ubuntu 19.04 [Vagrant box](https://app.vagrantup.com/xkrt/boxes/ubuntu-19.04), I tried to produce a same environment as you do
- install dependent libraries to match what you provided `build-essential libbz2-dev libcurl4-openssl-dev`. 
- the `./configure` output matches yours
- run the following commands

```bash
sudo apt install build-essential libbz2-dev libcurl4-openssl-dev
curl -O https://research.wand.net.nz/software/wandio/wandio-4.2.1.tar.gz
tar zxf wandio-4.2.1.tar.gz
cd wandio-4.2.1/
./configure
make
sudo make install
sudo ldconfig
wandiocat http://google.com
```

Wandiocat command succeeded in my test. 

To exclude possibility that your environment have outdated libcurl library, can you try reinstall the libcurl library (`libcurl4-openssl-dev`) and try make wandio again? 
If you still have problems after that, you could also try to enable more verbose debug information by enabling libcurl verbose options at the following line:
https://github.com/wanduow/wandio/blob/master/lib/ior-http.c#L294
(Change value passed to `CURLOPT_VERBOSE` from `0L` to `1L` and rebuild).

Please let us know if the problem still persists. Thanks!

**Comment by Intissar-Addali** [comment] 2019-06-19 14:15
Thank you very much for you answer.
I succeeded in solving he problem. Indeed, it was a proxy error, so I fixed it using
`$ export https_proxy = my_proxy
$ export http_proxy = my_proxy`
Now, everything works well.
PS: the curlopt_verbose did not change the result.

**Comment by digizeph** [comment] 2019-06-19 14:49
Great! I will close this issue now. Feel free to open new issues if you encounter any new problems.

**Closed by digizeph** 2019-06-19 14:49 UTC
