### ISSUE TITLE
Wandio not compiling on Ubuntu 16.04. Problem with libcurl linking lib.

### ISSUE THREAD

**Issue by galileo100584** [CAIDA/bgpstream#25] opened 2016-06-09 10:30 UTC
After this command:
“leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ ./configure”

I get this status:
configure: WANDIO version 1.0.3
configure: Compiled with compressed file (zlib) support: Yes
configure: Compiled with compressed file (bz2) support: Yes
configure: Compiled with compressed file (lzo write only) support: No
configure: Compiled with compressed file (lzma) support: No
configure: Compiled with http read (libcurl) support: Yes

It is the requierment from the guide:
https://bgpstream.caida.org/docs/install/bgpstream

After this command:
“leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ make”

I get this error message:
make  all-recursive
make[1]: Entering directory '/home/leo/src/wandio-1.0.3'
Making all in lib
make[2]: Entering directory '/home/leo/src/wandio-1.0.3/lib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/leo/src/wandio-1.0.3/lib'
Making all in tools/wandiocat
make[2]: Entering directory '/home/leo/src/wandio-1.0.3/tools/wandiocat'
  CCLD   wandiocat
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_global_init@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_perform@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_init@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_fdset@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_multi_timeout@CURL_OPENSSL_3'
/home/leo/src/wandio-1.0.3/lib/.libs/libwandio.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
collect2: error: ld returned 1 exit status
Makefile:335: recipe for target 'wandiocat' failed
make[2]: *** [wandiocat] Error 1
make[2]: Leaving directory '/home/leo/src/wandio-1.0.3/tools/wandiocat'
Makefile:347: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/leo/src/wandio-1.0.3'
Makefile:278: recipe for target 'all' failed
make: *** [all] Error 2

Location of libcurl is:
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ find /usr -name "libcurl.so"
/usr/local/lib/libcurl.so
/usr/lib/x86_64-linux-gnu/libcurl.so

I compiled curl from src to get past the dependency of wandio. But now it does not seem to find libcurl when running “make”. 

Does anybody have a suggestions or some tips?

**Comment by galileo100584** [comment] 2016-06-09 12:28
I have removed the compiled version of libcurl:
Now I only have the installed from package manager:
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ find /usr -name "libcurl.so"
/usr/lib/x86_64-linux-gnu/libcurl.so

"make & make install" works fine, but when i try to test i get this error:
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ wandiocat http://google.com
wandiocat: error while loading shared libraries: libwandio.so.1: cannot open shared object file: No such file or directory

This can be solved my exporting a path variable:
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ find /usr -name "libwandio.so.1"
/usr/local/lib/libwandio.so.1
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"

Now the test works:
leo@leo-XPS-13-9343:~/src/wandio-1.0.3$ wandiocat http://google.com
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="no">..............

**Comment by alistairking** [comment] 2016-06-13 16:36
I'm glad you figured out how to get it to build.
A couple of comments:
 - it seems like your first problem may have been caused by not having the curl development headers installed. There are some OS-specific install guides at https://bgpstream.caida.org/docs/install/bgpstream which list the packages needed. Which OS are you using?
 - the "error while loading shared libraries" problem can often be resolved by running `sudo ldconfig`

**Comment by alistairking** [comment] 2016-07-15 17:08
@galileo100584 I'm going to close this issue, if you have any updates or comments please feel free to reopen it.

**Closed by alistairking** 2016-07-15 17:08 UTC
