### ISSUE TITLE
Memory leak with bgpstream ?

### ISSUE THREAD

**Issue by ksalamat** [CAIDA/bgpstream#80] opened 2019-01-10 20:59 UTC
Hi

I am using the bgpstream library to capture bgp streams over all RIPE collectors over long period of times to construct AS graphs snapsnots. The problem I have is stall after adding my collectors through bgpstream_add_filter(bs, BGPSTREAM_FILTER_TYPE_COLLECTOR,...) and launching the bgpstream_start(.) and just after the  bgpstream_record_get_next_elem(record) my memory footprint increase in one second to 800 MB and keep increasing with time. I have been able after extensive memory profiling to figure out that the memory inflation is occuring into the stream data structure. Have you an idea what is causing this. A memory leak in bgpstream ?

**Comment by alistairking** [comment] 2019-01-10 21:15
It is possible that it is a memory leak, but it is quite normal for BGPStream to use a lot of memory when processing data as it buffers data from each dump file in memory while it is consumed.
You could try setting the `LIBTRACEIO=nothreads` environment variable to force the IO to happen in a single thread (and thus drastically reduce the amount of data buffered) and see if that makes a difference.

**Comment by ksalamat** [comment] 2019-01-11 19:43
Hi  Alistair, 
I have done as you suggested an. the memory is indeed reduced (and the speed also :-( ) But the issue is that even with a single thread the memory keeps growing and reach as large as several GB for two hours of BGP updates capture. I will have no issue with a large amount of memory as long as it does not keep growing ...

**Comment by alistairking** [comment] 2019-01-11 20:15
Can you confirm if you are using BGPStream v1 or the v2 beta?
We have v1 processes running for many months (if not years) continuously processing data and have not had any problems with memory leaks (indeed we are usually very careful to check for memory leaks with valgrind).
Would you mind sharing enough your code to help me reproduce the problem?

**Comment by LukeFenton** [comment] 2019-03-06 15:53
Hi, 

I have been using the pybgpstream V2 to pull in all of the data from Routeviews Update Messages for processing continuously. 

I have noticed that after running for 10-20 minutes the memory usage appears to continuously increase until the machine hits 100% and falls over.

I have only noticed this while using V2 and don't know whether this issue is related to this.

**Comment by alistairking** [comment] 2019-03-06 15:58
@LukeFenton thanks for the report. We have had another report of a memory leak in PyBGPStream v2 and are actually looking into this at the moment.
Just to be clear, this issue only affects the V2 beta, not the V1 release.

**Comment by LukeFenton** [comment] 2019-03-06 16:06
That seems to be correct, I have not seen any memory leaks in the V1

**Comment by ksalamat** [comment] 2019-03-06 17:01
Have a similar problem with v2

Kv

**Comment by ksalamat** [comment] 2019-03-17 15:44
Hi,

Have a question relative to the memory leak. 

I have an application that read 20 BGP feeds (RPE’s one) and process the updates over long time. I am using the classical while loop
   while (bgpstream_get_next_record(bs, &record) > 0) {
...
        while (bgpstream_record_get_next_elem(record, &elem)>0) {
….

And process elem variable. However I have the feeling that the allocated record are not deallocated and that they remain in memory resulting into up to 30 G of RAM used after 20 mins of  running. I saw that there is a function  bgpstream_record_destroy(record); but it should be called outside the loop.

How can I deallocated memory used by records that I have already processed ?

Many thanks for your answer

Kv

**Comment by alistairking** [comment] 2019-03-18 01:50
Can you confirm that you have this same issue when using the bgpreader tool? It is using the same API, and so if there is a memory leak it should be present there too.

And just to make sure we're on the same page, we're talking about the latest V2 beta code, right?

**Comment by LukeFenton** [comment] 2019-03-22 10:17
Hi, Can i ask which API is being used for both the BGPreader tool and the pybgpstream ?

**Comment by alistairking** [comment] 2019-03-22 12:07
They both use the libbgpstream C library. The V1 version of this library is in this repo, the V2 version is in the libbgpstream library (due to some reorganization we did when developing V2).

**Comment by alistairking** [comment] 2019-04-05 18:03
@LukeFenton @ksalamat can you try using the latest pybgpstream version from https://github.com/CAIDA/pybgpstream and confirm that this fixes the memory leak?

**Comment by LukeFenton** [comment] 2019-04-08 09:42
@alistairking I will try the fix this morning and report back

**Comment by ksalamat** [comment] 2019-04-08 09:52
Hi Alistair,

I am not using pybgpstream, but rather directly the C library. I will test and tell you in the coming days.

Kv

**Comment by alistairking** [comment] 2019-04-08 14:08
@LukeFenton thanks

@ksalamat this fix does not affect libbgpstream, only pybgpstream. can you please provide a minimal example that we can use to reproduce the problem?

**Comment by ksalamat** [comment] 2019-04-08 21:29
Hi Alistair

> Le 8 avr. 2019 à 16:08, Alistair King <notifications@github.com> a écrit :
> 
> @LukeFenton <https://github.com/LukeFenton> thanks
> 
> @ksalamat <https://github.com/ksalamat> this fix does not affect libbgpstream, only pybgpstream. can you please provide a minimal example that we can use to reproduce the problem?
> 
> 
I think that I have another view on the leak problem, now. In fact I get BGP updates from 20 different collectors and the libbgpstream allocates  a huge buffer space. This space is kind of erratic. It goes sometime up to 2 G of RAM allocation and drop suddenly to 0. This make me wondering if am seeing a leak or something else. Finally I think it is not really leak but rather the unpredictability of memory allocation changes in libbgp. 

Rgds

Kv

**Comment by ksalamat** [comment] 2019-04-08 21:50
BTW Alistair

Get a lot of messages like that 
WARN: NOT_IMPLEMENTED: OPEN Capability 128 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 2 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 128 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 2 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 128 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 2 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 128 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)
WARN: NOT_IMPLEMENTED: OPEN Capability 2 is either unknown or currently unsupported (parsebgp_bgp_open.c:103)

What do they means ?

Kv

**Comment by LukeFenton** [comment] 2019-04-23 12:49
@alistairking Hi Sorry for the delay in replying. Busy busy...from the initial tests it looks as if the update has fixed the leak. Though a quick question is the same as the comment from @ksalamat, can you describe what these warnings are ?

Thanks

Luke

**Comment by alistairking** [comment] 2019-04-23 13:43
@ksalamat @LukeFenton those messages are when the parser finds an attribute, or in this case, an OPEN capability that it does not understand. Here you can see that Capabilities 2 and 128 are found but not understood by the parser. See https://www.iana.org/assignments/capability-codes/capability-codes.xhtml for more information about capability codes.

I'm going to close this issue now as the original question has been answered (afaik). Please feel free to reopen if your memory leak problem is not resolved.

**Closed by alistairking** 2019-04-23 13:43 UTC
