### ISSUE TITLE
-k parameter for prefixes

### ISSUE THREAD

**Issue by fartbagxp** [CAIDA/bgpstream#56] opened 2018-01-01 20:44 UTC
Hi, I'm pretty new to this, and I've been trying out bgp stream for the past hour or so.

I'm trying to filter down the results by prefixes using the `-k` parameter, and I'm running into some difficulties.

My current command looks a little like this: `bgpstream -w 1514836552 -k 10.0.0.1/32 -p ris -m`
And I know 10.0.0.1/32 isn't supposed to match anything at all, but it still gives me results for other prefixes match, which leads me to think I'm using it wrong.

My intention is to filter down results returned to a particular set of prefixes, and I was wondering if there's any way of doing that.

Thanks!

**Comment by alistairking** [comment] 2018-01-03 13:33
Hey, thanks for using BGPStream.

This seems to be a duplicate of Issue #49. Currently filters aren't supported when using the `-m` option.

**Closed by alistairking** 2018-01-03 13:33 UTC
