### ISSUE TITLE
Broker request failed

### ISSUE THREAD

**Issue by Toppyo** [CAIDA/bgpstream#66] opened 2018-05-25 06:20 UTC
Hi:

I am using Mac OSX. And after I installed the required dependencies, I ran the example on my terminal and it just keeps giving me errors as follows:

```
Sylars-MacBook-Pro:bgpstream sylar$ bgpreader -w 1444492200,1444493400 -c rrc04  -m 
ERROR: Could not open https://bgpstream.caida.org/broker/data?collectors[]=rrc04&intervals[]=1444492200,1444493400 for reading
WARN: Broker request failed, waiting 1s before retry
ERROR: Could not open https://bgpstream.caida.org/broker/data?collectors[]=rrc04&intervals[]=1444492200,1444493400 for reading
WARN: Broker request failed, waiting 2s before retry
ERROR: Could not open https://bgpstream.caida.org/broker/data?collectors[]=rrc04&intervals[]=1444492200,1444493400 for reading
WARN: Broker request failed, waiting 4s before retry
ERROR: Could not open https://bgpstream.caida.org/broker/data?collectors[]=rrc04&intervals[]=1444492200,1444493400 for reading
WARN: Broker request failed, waiting 8s before retry
ERROR: Could not open https://bgpstream.caida.org/broker/data?collectors[]=rrc04&intervals[]=1444492200,1444493400 for reading
WARN: Broker request failed, waiting 16s before retry
Terminated: 15
```

I would appreciate it if you can help me out with it!

**Comment by Toppyo** [comment] 2018-05-25 07:41
And I manually checked the https link through safari, and it seems working fine.

```
{"time":1527233960,"type":"data","error":null,"queryParameters":{"human":false,"projects":[],"project":null,"collectors":["rrc04"],"collector":null,"intervals":["1444492200,1444493400 for reading"],"types":[],"type":null,"minInitialTime":null,"dataAddedSince":null,"debug":{"numFiles":7,"intervals":["1444492200,1444493400"]}},"data":{"dumpFiles":[{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444491900.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444491900,"duration":300},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444492200.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444492200,"duration":300},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444492500.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444492500,"duration":300},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/ribs\/2015\/10\/10\/ris.rrc04.ribs.1444492800.gz","project":"ris","collector":"rrc04","type":"ribs","initialTime":1444492800,"duration":120},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444492800.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444492800,"duration":300},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444493100.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444493100,"duration":300},{"urlType":"simple","url":"http:\/\/bgp-archive.caida.org\/ris\/rrc04\/updates\/2015\/10\/10\/ris.rrc04.updates.1444493400.gz","project":"ris","collector":"rrc04","type":"updates","initialTime":1444493400,"duration":300}]}}
```

**Comment by digizeph** [comment] 2018-05-25 15:55
@Toppyo I cannot reproduce the problem on my machine, maxOS 10.13.4 and master branch. I also tried the release tarball. Still cannot reproduce the problem. I suspect that it was a problem at the wandio side. Could you double check if wandio is installed correctly? Thanks!

**Comment by Toppyo** [comment] 2018-05-26 08:52
Thank your for your reply so soon and I agree on your point. These is not much on the internet about wandio, so I just ran a simple commend using wandio, and the commend and the result is as follows:
```
Sylars-MacBook-Pro:bgpstream sylar$ wandiocat http://www.apple.com/library/test/success.html
<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>Sylars-MacBook-Pro:bgpstream sylar$ 
```
So it seems my system can allocate the wandio lib somehow.

**Comment by Toppyo** [comment] 2018-05-28 01:21
Hi, I checked other links for wandiocat. Seems they all failed except the apple-example one. (see as below)
```
Sylars-MacBook-Pro:wandio sylar$ wandiocat www.google.com
Failed to open www.google.com
```
And then I start looking into config.log file in wandio's folder and I found this:
```
conftest.c:14:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
configure:4848: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "wandio"
| #define PACKAGE_TARNAME "wandio"
| #define PACKAGE_VERSION "1.0.4"
| #define PACKAGE_STRING "wandio 1.0.4"
| #define PACKAGE_BUGREPORT "contact@wand.net.nz"
| #define PACKAGE_URL ""
| #define PACKAGE "wandio"
| #define VERSION "1.0.4"
| #define WANDIO_MAJOR ${WANDIO_MAJOR}
| #define WANDIO_MID ${WANDIO_MID}
| #define WANDIO_MINOR ${WANDIO_MINOR}
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
```
[config.log](https://github.com/CAIDA/bgpstream/files/2043247/config.log)

**Comment by Toppyo** [comment] 2018-05-28 01:43
Seems like the autoconf doesn't recognize my system as an OS system, instead it recognize my system as a Linux system. Am I taking the right steps? Cuz it is my first time to come across a problem like this :P

To be specific, my system is x86_64-apple-darwin17.2.0

**Comment by Toppyo** [comment] 2018-05-28 02:55
@digizeph My apology. When I use commend as follows, wandiocat works just fine:
```
wandiocat http://google.com
```
Results:
```
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ja"><head><meta content="&#19990;&#30028;&#20013;&#12398;&#12354;&#12425;&#12422;&#12427;&#24773;&#22577;&#12434;&#26908;&#32034;&#12377;&#12427;&#12383;&#12417;&#12398;&#12484;&#12540;&#12523;&#12434;&#25552;&#20379;&#12375;&#12390;&#12356;&#12414;&#12377;&#12290;&#12373;&#12414;&#12374;&#12414;&#12394;&#26908;&#32034;&#27231;&#33021;&#12434;&#27963;&#29992;&#12375;&#12390;&#12289;&#12362;&#25506;&#12375;&#12398;&#24773;&#22577;&#12434;&#35211;&#12388;&#12369;&#12390;&#12367;&#12384;&#12373;&#12356;&#12290;" name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
...
```
So the problem may not come from the wandio's side.

**Comment by alistairking** [comment] 2018-05-29 17:30
Hey @Toppyo,

Can you confirm that you are still having this problem?
I mean, can you try running bgpstream again to be sure that it wasn't some transient problem with the broker service.

**Comment by alistairking** [comment] 2018-06-29 17:31
I'm going to assume this is no longer a problem and close the issue. Feel free to re-open if you're still having problems.

**Closed by alistairking** 2018-06-29 17:31 UTC
